name=input("what is your name?: ")
surname=input("what is your surname?: ")
age=input("what is your age?: ")
email=input("what is your email?: ")
username=input("choose your username: ")
password=input("create your password: ")
print("he's name is "+ name+" ""he's surname is "+surname+" "+"he's age is "+age+" "+"he's email is "+ email+" "+"he's username is "+username+" "+"he's password will be"+password)