
new_user=input("whats your name:")
surname=input("whats your surname:")
age=input("what is your age:")
what_time=input("if you can travel in time what year would you choose:")
what_time_age=input("what age you will be in your choosen year")
print("man tqva rom mas qvia"+ new_user)
print("man tqva rom misi gvaria"+ surname)
print("man tqva rom is aris"+ age+ " wlis")
ptint("is imogzaurebda"+ what_time+" wels")
print("mogzaurobis dros is iqneboda"+ what_time_age+" wlis")