new_user=input(" whats your name: ")
surname=input(" whats your surname: ")
birth_year=input(" what is your birth year: ")
what_time=input(" if you can travel in time what year would you choose: ")
after_travel=str((int(what_time) - int(birth_year)))
print("you wil be " +after_travel+ " age in "+ what_time)
print("man tqva rom mas qvia " + new_user)
print("man tqva rom misi gvaria " + surname)
print("man tqva rom is aris "+ birth_year + " wels dabadebuli")
print("is imogzaurebda "+ what_time +" wels")
print("mogzaurobis dros is iqneboda "+ after_travel + " wlis")